CreateUsersTable: create table `users` (`id` bigint unsigned not null auto_increment primary key, `name` varchar(255) not null, `email` varchar(255) not null, `email_verified_at` timestamp null, `password` varchar(255) not null, `remember_token` varchar(100) null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
CreateUsersTable: alter table `users` add unique `users_email_unique`(`email`)
CreatePasswordResetsTable: create table `password_resets` (`email` varchar(255) not null, `token` varchar(255) not null, `created_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
CreatePasswordResetsTable: alter table `password_resets` add index `password_resets_email_index`(`email`)
CriarTabelaInfracoes: create table `infracoes` (`id` bigint unsigned not null auto_increment primary key, `tipo` enum('Internet', 'Presencial') not null, `tipo_produto` enum('composto_lacteo', 'formula_infantil', 'leites') not null, `empresa` varchar(255) not null, `marca` varchar(255) not null, `estado` enum('AC', 'AL', 'AM', 'AP', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA', 'MT', 'MS', 'MG', 'PA', 'PB', 'PR', 'PE', 'PI', 'RJ', 'RN', 'RO', 'RS', 'RR', 'SC', 'SE', 'SP', 'TO') not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
CreateEnderecosTable: create table `enderecos` (`id` bigint unsigned not null auto_increment primary key, `logradouro` varchar(255) not null, `numero` varchar(255) not null, `bairro` varchar(255) not null, `cidade` varchar(255) not null, `estado` varchar(255) not null, `id_user` bigint unsigned not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
CreateEnderecosTable: alter table `enderecos` add constraint `enderecos_id_user_foreign` foreign key (`id_user`) references `users` (`id`) on delete cascade
CreateInstituicaosTable: create table `instituicoes` (`id` bigint unsigned not null auto_increment primary key, `orgao` varchar(255) not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
CreateVacinasTable: create table `vacinas` (`id` bigint unsigned not null auto_increment primary key, `nome` varchar(255) not null, `instituicao_id` bigint unsigned not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
CreateVacinasTable: alter table `vacinas` add constraint `vacinas_instituicao_id_foreign` foreign key (`instituicao_id`) references `instituicoes` (`id`)
CreateUserVacinasTable: create table `user_vacinas` (`id` bigint unsigned not null auto_increment primary key, `id_user` bigint unsigned not null, `id_vacina` bigint unsigned not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
CreateUserVacinasTable: alter table `user_vacinas` add constraint `user_vacinas_id_user_foreign` foreign key (`id_user`) references `users` (`id`) on delete cascade
CreateUserVacinasTable: alter table `user_vacinas` add constraint `user_vacinas_id_vacina_foreign` foreign key (`id_vacina`) references `vacinas` (`id`) on delete cascade
AdicionarCpfEmUsers: alter table `users` add `cpf` varchar(255) not null after `email`
AdicionarCpfEmUsers: alter table `users` add unique `users_cpf_unique`(`cpf`)
CriarTabelaPapeis: create table `papeis` (`id` bigint unsigned not null auto_increment primary key, `nome` varchar(255) not null, `descricao` varchar(255) not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
CriarTabelaPermissoes: create table `permissoes` (`id` bigint unsigned not null auto_increment primary key, `nome` varchar(255) not null, `descricao` varchar(255) not null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
CriarTabelaPapeisPermissoes: create table `papeis_permissoes` (`papel_id` bigint unsigned not null, `permissao_id` bigint unsigned not null) default character set utf8mb4 collate 'utf8mb4_unicode_ci'
CriarChavesAcl: alter table `users` add `papel_id` bigint unsigned not null
CriarChavesAcl: alter table `users` add constraint `users_papel_id_foreign` foreign key (`papel_id`) references `papeis` (`id`)
CriarChavesAcl: alter table `papeis_permissoes` add constraint `papeis_permissoes_papel_id_foreign` foreign key (`papel_id`) references `papeis` (`id`)
CriarChavesAcl: alter table `papeis_permissoes` add constraint `papeis_permissoes_permissao_id_foreign` foreign key (`permissao_id`) references `permissoes` (`id`)
